---
- hosts: all
  tasks:
  - name: install nginx
    package:
     name: nginx
     state: present

  - template:
     src: index.nginx-debian.html
     dest: /var/www/html/index.html
     owner: root
     mode: "u=rw,g=r,o=r"
     
  - file:
     state: absent
     path: /etc/nginx/sites-enabled/default
     
  - template:
     src: app.conf
     dest: /etc/nginx/sites-enabled/app.conf
     owner: root
     mode: "u=rw,g=r,o=r"
     
  - name: restart nginx
    service:
      name: nginx
      state: restarted
